PR: IN Profile Listings Page
hatchways/team-gingerbread pull request #93
Opened 2021-12-05 03:06 UTC by ababber

### What this PR does (required):
- updated profile listings page with backend get route to load multiple users based on isSitter property in db, integrated FE and BE so that profile listings page loads data from db

### Screenshots / Videos (front-end only):
https://user-images.githubusercontent.com/18492009/144731795-d1f2880c-89e7-4f1f-8d0e-e1a7b0b39f2e.mov

### Any information needed to test this feature (required):
- team-gingerbread s3 bucket access required, load app, add users with isSitter set to true and upload pictures, navigate to profile listings page, and the new users created with will be loaded to profile listings page

### Any issues with the current functionality (optional):
- profile listings page is not integrated with landing page and does not load based on address
- cannot load based on availability because feature is not complete
- the load more button does not work because the get route only retrieves a fixed amount of users, dynamic calls to the db needs to be added

2021-12-05 15:23 UTC, ezeilo-su requested changes
Nice integration. Just left a few comments for you to have a look. Please also resolve the merge conflict in this branch.

2021-12-05 15:23 UTC, ezeilo-su commented on server/controllers/deleteImage.js
> +// @access Private
:+1:

2021-12-05 15:23 UTC, ezeilo-su commented on server/controllers/uploadImage.js
> +// @access Private
:+1:

2021-12-05 15:23 UTC, ezeilo-su commented on client/src/pages/ProfileListings/ProfileListings.tsx
> +          onClick={() => console.log('load more users')}
Please let's get rid of this console log

2021-12-07 10:34 UTC, ababber commented on server/controllers/updateIsSitter.js
> +  });
Changed in the following commit: https://github.com/hatchways/team-gingerbread/pull/93/commits/f1ad6780a1fdf1a99667d7729fc694ad58526f1a

2021-12-08 02:59 UTC, ababber commented on server/controllers/updateIsSitter.js
> +  const { _id } = req.query;
Fixed in the following commit: https://github.com/hatchways/team-gingerbread/pull/90/commits/eba2d2f159c0699b085c3921a500fe1be51ed898

2021-12-10 21:28 UTC, rajivtitus commented on client/src/components/EditProfile/EditProfileTab/EditProfileTab.tsx
> +                <Typography className={classes.label}>i&apos;m a sitter</Typography>
```suggestion
                <Typography className={classes.label}>
                  {isSitter ? "i'm a sitter" : "i'm not a sitter"}
                 </Typography>
```

2021-12-10 21:30 UTC, rajivtitus commented on client/src/components/EditProfile/ProfilePhotoTab/ProfilePhotoTab.tsx
> +          if (data.error) updateSnackBarMessage('An error occurred while uploading the image.');
Good work making these small changes but resort to making them in a separate PR :)

2021-12-10 21:36 UTC, rajivtitus commented on client/src/pages/ProfileListings/ProfilePreview/ProfilePreview.tsx
> +      <CardContent className={classes.content}>
```suggestion
      <CardActionArea comopnent={Link} to=`/profile-details/${profile.id}`
      <CardContent className={classes.content}>
```
Adding the cardaction area here to navigate from the listing page to the details page would a nice tough 👍🏽

2021-12-10 21:43 UTC, rajivtitus commented on server/controllers/profile.js
> +  const { numOfUsers } = req.query;
Good work! Additionally, you can have pagination with page numbers/ profiles per page :)

A video I found on the internet: https://www.youtube.com/watch?v=soWg_UtD_AM

2021-12-10 21:44 UTC, rajivtitus approved these changes
Great work Ankit! Just a couple of minor comments for you to address before merging 👍🏽

2021-12-18 02:36 UTC, merged